C: 1.0
class_weight:
dual: false
fit_intercept: true
intercept_scaling: 1
l1_ratio:
max_iter: 100
multi_class: auto
n_jobs:
penalty: l2
random_state:
solver: lbfgs
tol: 0.0001
verbose: 0
warm_start: false
